# Generated by Django 3.2.4 on 2021-11-03 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_file', models.FileField(upload_to='uploaded_logs')),
                ('log_name', models.CharField(max_length=500)),
                ('log_name2', models.CharField(max_length=100)),
            ],
        ),
    ]
